{'2020-06-25 01:36:05.869860': 'Traceback (most recent call last):\n  File "C:\\Users\\domin\\PycharmProjects\\td-backend\\flask_apis\\User.py", line 39, in registration\n    db_access.create_document(password, birthday)\n  File "C:\\Users\\domin\\PycharmProjects\\td-backend\\database_access\\DbAccess.py", line 49, in create_document\n    file = open(r"D:\\Users\\Dominic\\training-diary-app\\database_access\\initial_data", "rb")\nFileNotFoundError: [Errno 2] No such file or directory: \'D:\\\\Users\\\\Dominic\\\\training-diary-app\\\\database_access\\\\initial_data\'\n'}
{'2020-06-25 01:36:19.843346': 'Traceback (most recent call last):\n  File "C:\\Users\\domin\\PycharmProjects\\td-backend\\flask_apis\\User.py", line 39, in registration\n    db_access.create_document(password, birthday)\n  File "C:\\Users\\domin\\PycharmProjects\\td-backend\\database_access\\DbAccess.py", line 49, in create_document\n    file = open(r"D:\\Users\\Dominic\\training-diary-app\\database_access\\initial_data", "rb")\nFileNotFoundError: [Errno 2] No such file or directory: \'D:\\\\Users\\\\Dominic\\\\training-diary-app\\\\database_access\\\\initial_data\'\n'}
{'2020-06-28 01:43:16.004568': 'Traceback (most recent call last):\n  File "C:\\Users\\domin\\PycharmProjects\\td-backend\\flask_apis\\User.py", line 66, in get_all_data\n    return self.__generate_success_response(self.__auth.get_db_access().get_all_data())\n  File "C:\\Users\\domin\\PycharmProjects\\td-backend\\database_access\\DbAccess.py", line 28, in get_all_data\n    data = self.__document.copy()\nAttributeError: \'NoneType\' object has no attribute \'copy\'\n'}
{'2020-06-28 01:50:10.286034': 'Traceback (most recent call last):\n  File "C:\\Users\\domin\\PycharmProjects\\td-backend\\flask_apis\\User.py", line 66, in get_all_data\n    return self.__generate_success_response(self.__auth.get_db_access().get_all_data())\n  File "C:\\Users\\domin\\PycharmProjects\\td-backend\\database_access\\DbAccess.py", line 28, in get_all_data\n    data = self.__document.copy()\nAttributeError: \'NoneType\' object has no attribute \'copy\'\n'}
{'2020-06-28 01:52:46.305049': 'Traceback (most recent call last):\n  File "C:\\Users\\domin\\PycharmProjects\\td-backend\\flask_apis\\User.py", line 66, in get_all_data\n    return self.__generate_success_response(self.__auth.get_db_access().get_all_data())\n  File "C:\\Users\\domin\\PycharmProjects\\td-backend\\database_access\\DbAccess.py", line 28, in get_all_data\n    data = self.__document.copy()\nAttributeError: \'NoneType\' object has no attribute \'copy\'\n'}
{'2020-06-28 01:56:58.385687': 'Traceback (most recent call last):\n  File "C:\\Users\\domin\\PycharmProjects\\td-backend\\flask_apis\\User.py", line 66, in get_all_data\n    return self.__generate_success_response(self.__auth.get_db_access().get_all_data())\n  File "C:\\Users\\domin\\PycharmProjects\\td-backend\\database_access\\DbAccess.py", line 28, in get_all_data\n    data = self.__document.copy()\nAttributeError: \'NoneType\' object has no attribute \'copy\'\n'}
{'2020-06-28 02:00:01.889090': 'Traceback (most recent call last):\n  File "C:\\Users\\domin\\PycharmProjects\\td-backend\\flask_apis\\User.py", line 66, in get_all_data\n    return self.__generate_success_response(self.__auth.get_db_access().get_all_data())\n  File "C:\\Users\\domin\\PycharmProjects\\td-backend\\database_access\\DbAccess.py", line 28, in get_all_data\n    data = self.__document.copy()\nAttributeError: \'NoneType\' object has no attribute \'copy\'\n'}
{'2020-06-28 02:30:53.554848': 'Traceback (most recent call last):\n  File "C:\\Users\\domin\\PycharmProjects\\td-backend\\flask_apis\\User.py", line 66, in get_all_data\n    return self.__generate_success_response(self.__auth.get_db_access().get_all_data())\n  File "C:\\Users\\domin\\PycharmProjects\\td-backend\\database_access\\DbAccess.py", line 28, in get_all_data\n    data = self.__document.copy()\nAttributeError: \'NoneType\' object has no attribute \'copy\'\n'}
{'2020-06-28 02:34:32.610089': 'Traceback (most recent call last):\n  File "C:\\Users\\domin\\PycharmProjects\\td-backend\\flask_apis\\User.py", line 66, in get_all_data\n    return self.__generate_success_response(self.__auth.get_db_access().get_all_data())\n  File "C:\\Users\\domin\\PycharmProjects\\td-backend\\database_access\\DbAccess.py", line 28, in get_all_data\n    data = self.__document.copy()\nAttributeError: \'NoneType\' object has no attribute \'copy\'\n'}
{'2020-07-11 01:19:18.059120': 'Traceback (most recent call last):\n  File "D:\\Users\\Dominic\\training-diary-app\\flask_apis\\User.py", line 39, in registration\n    db_access.create_document(password, birthday)\n  File "D:\\Users\\Dominic\\training-diary-app\\database_access\\DbAccess.py", line 49, in create_document\n    file = open(r"C:\\Users\\domin\\PycharmProjects\\td-backend\\database_access\\initial_data", "rb")\nFileNotFoundError: [Errno 2] No such file or directory: \'C:\\\\Users\\\\domin\\\\PycharmProjects\\\\td-backend\\\\database_access\\\\initial_data\'\n'}
{'2020-07-11 01:19:25.780236': 'Traceback (most recent call last):\n  File "D:\\Users\\Dominic\\training-diary-app\\flask_apis\\User.py", line 39, in registration\n    db_access.create_document(password, birthday)\n  File "D:\\Users\\Dominic\\training-diary-app\\database_access\\DbAccess.py", line 49, in create_document\n    file = open(r"C:\\Users\\domin\\PycharmProjects\\td-backend\\database_access\\initial_data", "rb")\nFileNotFoundError: [Errno 2] No such file or directory: \'C:\\\\Users\\\\domin\\\\PycharmProjects\\\\td-backend\\\\database_access\\\\initial_data\'\n'}
{'2020-07-11 01:19:41.958369': 'Traceback (most recent call last):\n  File "D:\\Users\\Dominic\\training-diary-app\\flask_apis\\User.py", line 39, in registration\n    db_access.create_document(password, birthday)\n  File "D:\\Users\\Dominic\\training-diary-app\\database_access\\DbAccess.py", line 49, in create_document\n    file = open(r"C:\\Users\\domin\\PycharmProjects\\td-backend\\database_access\\initial_data", "rb")\nFileNotFoundError: [Errno 2] No such file or directory: \'C:\\\\Users\\\\domin\\\\PycharmProjects\\\\td-backend\\\\database_access\\\\initial_data\'\n'}
{'2020-07-11 01:23:49.691731': 'Traceback (most recent call last):\n  File "D:\\Users\\Dominic\\training-diary-app\\flask_apis\\User.py", line 66, in get_all_data\n    return self.__generate_success_response(self.__auth.get_db_access().get_all_data())\n  File "D:\\Users\\Dominic\\training-diary-app\\database_access\\DbAccess.py", line 28, in get_all_data\n    data = self.__document.copy()\nAttributeError: \'NoneType\' object has no attribute \'copy\'\n'}
{'2020-07-11 18:04:58.528736': 'Traceback (most recent call last):\n  File "D:\\Users\\Dominic\\training-diary-app\\flask_apis\\User.py", line 66, in get_all_data\n    return self.__generate_success_response(self.__auth.get_db_access().get_all_data())\n  File "D:\\Users\\Dominic\\training-diary-app\\database_access\\DbAccess.py", line 28, in get_all_data\n    data = self.__document.copy()\nAttributeError: \'NoneType\' object has no attribute \'copy\'\n'}
{'2020-07-11 18:21:30.164193': 'Traceback (most recent call last):\n  File "D:\\Users\\Dominic\\training-diary-app\\flask_apis\\User.py", line 66, in get_all_data\n    return self.__generate_success_response(self.__auth.get_db_access().get_all_data())\n  File "D:\\Users\\Dominic\\training-diary-app\\database_access\\DbAccess.py", line 28, in get_all_data\n    data = self.__document.copy()\nAttributeError: \'NoneType\' object has no attribute \'copy\'\n'}
{'2020-07-11 18:35:15.757503': 'Traceback (most recent call last):\n  File "D:\\Users\\Dominic\\training-diary-app\\flask_apis\\User.py", line 66, in get_all_data\n    return self.__generate_success_response(self.__auth.get_db_access().get_all_data())\n  File "D:\\Users\\Dominic\\training-diary-app\\database_access\\DbAccess.py", line 28, in get_all_data\n    data = self.__document.copy()\nAttributeError: \'NoneType\' object has no attribute \'copy\'\n'}
{'2020-07-11 18:42:26.840138': 'Traceback (most recent call last):\n  File "D:\\Users\\Dominic\\training-diary-app\\flask_apis\\User.py", line 66, in get_all_data\n    return self.__generate_success_response(self.__auth.get_db_access().get_all_data())\n  File "D:\\Users\\Dominic\\training-diary-app\\database_access\\DbAccess.py", line 28, in get_all_data\n    data = self.__document.copy()\nAttributeError: \'NoneType\' object has no attribute \'copy\'\n'}
{'2020-07-12 03:36:56.130417': 'Traceback (most recent call last):\n  File "D:\\Users\\Dominic\\training-diary-app\\flask_apis\\User.py", line 66, in get_all_data\n    return self.__generate_success_response(self.__auth.get_db_access().get_all_data())\n  File "D:\\Users\\Dominic\\training-diary-app\\database_access\\DbAccess.py", line 28, in get_all_data\n    data = self.__document.copy()\nAttributeError: \'NoneType\' object has no attribute \'copy\'\n'}
{'2020-07-13 02:07:03.144032': 'Traceback (most recent call last):\n  File "D:\\Users\\Dominic\\training-diary-app\\flask_apis\\User.py", line 66, in get_all_data\n    return self.__generate_success_response(self.__auth.get_db_access().get_all_data())\n  File "D:\\Users\\Dominic\\training-diary-app\\database_access\\DbAccess.py", line 28, in get_all_data\n    data = self.__document.copy()\nAttributeError: \'NoneType\' object has no attribute \'copy\'\n'}
{'2020-07-13 02:09:19.801965': 'Traceback (most recent call last):\n  File "D:\\Users\\Dominic\\training-diary-app\\flask_apis\\User.py", line 66, in get_all_data\n    return self.__generate_success_response(self.__auth.get_db_access().get_all_data())\n  File "D:\\Users\\Dominic\\training-diary-app\\database_access\\DbAccess.py", line 28, in get_all_data\n    data = self.__document.copy()\nAttributeError: \'NoneType\' object has no attribute \'copy\'\n'}
{'2020-07-23 21:21:39.249573': 'Traceback (most recent call last):\n  File "D:\\Users\\Dominic\\training-diary-app\\flask_apis\\User.py", line 66, in get_all_data\n    return self.__generate_success_response(self.__auth.get_db_access().get_all_data())\n  File "D:\\Users\\Dominic\\training-diary-app\\database_access\\DbAccess.py", line 28, in get_all_data\n    data = self.__document.copy()\nAttributeError: \'NoneType\' object has no attribute \'copy\'\n'}
{'2020-07-23 21:31:01.386306': 'Traceback (most recent call last):\n  File "D:\\Users\\Dominic\\training-diary-app\\flask_apis\\User.py", line 66, in get_all_data\n    return self.__generate_success_response(self.__auth.get_db_access().get_all_data())\n  File "D:\\Users\\Dominic\\training-diary-app\\database_access\\DbAccess.py", line 28, in get_all_data\n    data = self.__document.copy()\nAttributeError: \'NoneType\' object has no attribute \'copy\'\n'}
{'2020-07-24 12:29:37.296828': 'Traceback (most recent call last):\n  File "D:\\Users\\Dominic\\training-diary-app\\flask_apis\\User.py", line 66, in get_all_data\n    return self.__generate_success_response(self.__auth.get_db_access().get_all_data())\n  File "D:\\Users\\Dominic\\training-diary-app\\database_access\\DbAccess.py", line 28, in get_all_data\n    data = self.__document.copy()\nAttributeError: \'NoneType\' object has no attribute \'copy\'\n'}
{'2020-07-24 15:55:07.647301': 'Traceback (most recent call last):\n  File "D:\\Users\\Dominic\\training-diary-app\\flask_apis\\User.py", line 66, in get_all_data\n    return self.__generate_success_response(self.__auth.get_db_access().get_all_data())\n  File "D:\\Users\\Dominic\\training-diary-app\\database_access\\DbAccess.py", line 28, in get_all_data\n    data = self.__document.copy()\nAttributeError: \'NoneType\' object has no attribute \'copy\'\n'}
{'2020-07-27 16:54:27.358656': 'Traceback (most recent call last):\n  File "D:\\Users\\Dominic\\training-diary-app\\flask_apis\\User.py", line 66, in get_all_data\n    return self.__generate_success_response(self.__auth.get_db_access().get_all_data())\n  File "D:\\Users\\Dominic\\training-diary-app\\database_access\\DbAccess.py", line 28, in get_all_data\n    data = self.__document.copy()\nAttributeError: \'NoneType\' object has no attribute \'copy\'\n'}
{'2020-07-27 17:04:24.599303': 'Traceback (most recent call last):\n  File "D:\\Users\\Dominic\\training-diary-app\\flask_apis\\User.py", line 66, in get_all_data\n    return self.__generate_success_response(self.__auth.get_db_access().get_all_data())\n  File "D:\\Users\\Dominic\\training-diary-app\\database_access\\DbAccess.py", line 28, in get_all_data\n    data = self.__document.copy()\nAttributeError: \'NoneType\' object has no attribute \'copy\'\n'}
{'2020-07-27 17:14:54.131028': 'Traceback (most recent call last):\n  File "D:\\Users\\Dominic\\training-diary-app\\flask_apis\\User.py", line 66, in get_all_data\n    return self.__generate_success_response(self.__auth.get_db_access().get_all_data())\n  File "D:\\Users\\Dominic\\training-diary-app\\database_access\\DbAccess.py", line 28, in get_all_data\n    data = self.__document.copy()\nAttributeError: \'NoneType\' object has no attribute \'copy\'\n'}
{'2020-07-27 17:19:01.732412': 'Traceback (most recent call last):\n  File "D:\\Users\\Dominic\\training-diary-app\\flask_apis\\User.py", line 66, in get_all_data\n    return self.__generate_success_response(self.__auth.get_db_access().get_all_data())\n  File "D:\\Users\\Dominic\\training-diary-app\\database_access\\DbAccess.py", line 28, in get_all_data\n    data = self.__document.copy()\nAttributeError: \'NoneType\' object has no attribute \'copy\'\n'}
{'2020-07-27 17:45:08.787309': 'Traceback (most recent call last):\n  File "D:\\Users\\Dominic\\training-diary-app\\flask_apis\\User.py", line 66, in get_all_data\n    return self.__generate_success_response(self.__auth.get_db_access().get_all_data())\n  File "D:\\Users\\Dominic\\training-diary-app\\database_access\\DbAccess.py", line 28, in get_all_data\n    data = self.__document.copy()\nAttributeError: \'NoneType\' object has no attribute \'copy\'\n'}
{'2020-07-27 17:47:52.507741': 'Traceback (most recent call last):\n  File "D:\\Users\\Dominic\\training-diary-app\\flask_apis\\User.py", line 66, in get_all_data\n    return self.__generate_success_response(self.__auth.get_db_access().get_all_data())\n  File "D:\\Users\\Dominic\\training-diary-app\\database_access\\DbAccess.py", line 28, in get_all_data\n    data = self.__document.copy()\nAttributeError: \'NoneType\' object has no attribute \'copy\'\n'}
{'2020-07-27 17:57:57.944087': 'Traceback (most recent call last):\n  File "D:\\Users\\Dominic\\training-diary-app\\flask_apis\\User.py", line 66, in get_all_data\n    return self.__generate_success_response(self.__auth.get_db_access().get_all_data())\n  File "D:\\Users\\Dominic\\training-diary-app\\database_access\\DbAccess.py", line 28, in get_all_data\n    data = self.__document.copy()\nAttributeError: \'NoneType\' object has no attribute \'copy\'\n'}
{'2020-07-28 16:30:11.846152': 'Traceback (most recent call last):\n  File "D:\\Users\\Dominic\\training-diary-app\\flask_apis\\User.py", line 66, in get_all_data\n    return self.__generate_success_response(self.__auth.get_db_access().get_all_data())\n  File "D:\\Users\\Dominic\\training-diary-app\\database_access\\DbAccess.py", line 28, in get_all_data\n    data = self.__document.copy()\nAttributeError: \'NoneType\' object has no attribute \'copy\'\n'}
{'2020-07-28 16:32:55.135233': 'Traceback (most recent call last):\n  File "D:\\Users\\Dominic\\training-diary-app\\flask_apis\\User.py", line 66, in get_all_data\n    return self.__generate_success_response(self.__auth.get_db_access().get_all_data())\n  File "D:\\Users\\Dominic\\training-diary-app\\database_access\\DbAccess.py", line 28, in get_all_data\n    data = self.__document.copy()\nAttributeError: \'NoneType\' object has no attribute \'copy\'\n'}
{'2020-07-28 17:50:45.528006': 'Traceback (most recent call last):\n  File "D:\\Users\\Dominic\\training-diary-app\\flask_apis\\User.py", line 66, in get_all_data\n    return self.__generate_success_response(self.__auth.get_db_access().get_all_data())\n  File "D:\\Users\\Dominic\\training-diary-app\\database_access\\DbAccess.py", line 28, in get_all_data\n    data = self.__document.copy()\nAttributeError: \'NoneType\' object has no attribute \'copy\'\n'}
{'2020-07-31 18:21:04.551225': 'Traceback (most recent call last):\n  File "D:\\Users\\Dominic\\training-diary-app\\flask_apis\\User.py", line 66, in get_all_data\n    return self.__generate_success_response(self.__auth.get_db_access().get_all_data())\n  File "D:\\Users\\Dominic\\training-diary-app\\database_access\\DbAccess.py", line 28, in get_all_data\n    data = self.__document.copy()\nAttributeError: \'NoneType\' object has no attribute \'copy\'\n'}
{'2020-07-31 18:25:07.870551': 'Traceback (most recent call last):\n  File "D:\\Users\\Dominic\\training-diary-app\\flask_apis\\User.py", line 66, in get_all_data\n    return self.__generate_success_response(self.__auth.get_db_access().get_all_data())\n  File "D:\\Users\\Dominic\\training-diary-app\\database_access\\DbAccess.py", line 28, in get_all_data\n    data = self.__document.copy()\nAttributeError: \'NoneType\' object has no attribute \'copy\'\n'}
{'2020-08-02 14:47:36.766561': 'Traceback (most recent call last):\n  File "C:\\Users\\Dominic\\AppData\\Roaming\\Python\\Python37\\site-packages\\werkzeug\\wrappers\\base_response.py", line 298, in status_code\n    self._status = "%d %s" % (code, HTTP_STATUS_CODES[code].upper())\nKeyError: <Response 0 bytes [401 UNAUTHORIZED]>\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "D:\\Users\\Dominic\\training-diary-app\\flask_apis\\User.py", line 67, in get_all_data\n    print(make_response({}, flask.Response(status=401)))\n  File "C:\\Users\\Dominic\\AppData\\Roaming\\Python\\Python37\\site-packages\\flask\\helpers.py", line 223, in make_response\n    return current_app.make_response(args)\n  File "C:\\Users\\Dominic\\AppData\\Roaming\\Python\\Python37\\site-packages\\flask\\app.py", line 2139, in make_response\n    rv.status_code = status\n  File "C:\\Users\\Dominic\\AppData\\Roaming\\Python\\Python37\\site-packages\\werkzeug\\wrappers\\base_response.py", line 300, in status_code\n    self._status = "%d UNKNOWN" % code\nTypeError: %d format: a number is required, not Response\n'}
{'2020-08-02 14:47:45.343605': 'Traceback (most recent call last):\n  File "C:\\Users\\Dominic\\AppData\\Roaming\\Python\\Python37\\site-packages\\werkzeug\\wrappers\\base_response.py", line 298, in status_code\n    self._status = "%d %s" % (code, HTTP_STATUS_CODES[code].upper())\nKeyError: <Response 0 bytes [401 UNAUTHORIZED]>\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "D:\\Users\\Dominic\\training-diary-app\\flask_apis\\User.py", line 67, in get_all_data\n    print(make_response({}, flask.Response(status=401)))\n  File "C:\\Users\\Dominic\\AppData\\Roaming\\Python\\Python37\\site-packages\\flask\\helpers.py", line 223, in make_response\n    return current_app.make_response(args)\n  File "C:\\Users\\Dominic\\AppData\\Roaming\\Python\\Python37\\site-packages\\flask\\app.py", line 2139, in make_response\n    rv.status_code = status\n  File "C:\\Users\\Dominic\\AppData\\Roaming\\Python\\Python37\\site-packages\\werkzeug\\wrappers\\base_response.py", line 300, in status_code\n    self._status = "%d UNKNOWN" % code\nTypeError: %d format: a number is required, not Response\n'}
{'2020-08-03 00:35:31.696386': 'Traceback (most recent call last):\n  File "D:\\Users\\Dominic\\training-diary-app\\flask_apis\\User.py", line 68, in get_all_data\n    return make_response(self.__auth.get_db_access().get_all_data(), 200, response_header)\n  File "D:\\Users\\Dominic\\training-diary-app\\database_access\\DbAccess.py", line 28, in get_all_data\n    data = self.__document.copy()\nAttributeError: \'NoneType\' object has no attribute \'copy\'\n'}
